name: 'Foundry VTT Module Bundle Analysis'
description: 'Analyze bundle size changes in pull requests for Foundry VTT modules'
author: 'David Raynes'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  
  pattern:
    description: 'Glob pattern for files to analyze'
    required: false
    default: './dist/**/*.{js,css}'
  
  exclude:
    description: 'Glob pattern for files to exclude from analysis'
    required: false
    default: '{./dist/**/*.map,./dist/**/*.d.ts}'
  
  strip-hash:
    description: 'Regex pattern to strip hashes from filenames for comparison'
    required: false
    default: '\\.[a-f0-9]{8}\\.'
  
  minimum-change-threshold:
    description: 'Minimum change in bytes to report'
    required: false
    default: '100'
  
  analyze-zip:
    description: 'Also analyze module.zip artifact size'
    required: false
    default: 'false'
  
  zip-files:
    description: 'Files and directories to include in module zip analysis (space-separated, relative to working-directory)'
    required: false
    default: 'module.json styles/ templates/ languages/ README.md LICENSE'
  
  working-directory:
    description: 'Directory containing built files after build'
    required: false
    default: 'dist'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build module
      shell: bash
      run: npm run build

    - name: Create module zip for analysis
      if: inputs.analyze-zip == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Create module zip with specified files
        FILES="${{ inputs.zip-files }}"
        
        # Filter to only include files that exist
        EXISTING_FILES=""
        for file in $FILES; do
          if [[ -e "$file" ]]; then
            EXISTING_FILES="$EXISTING_FILES $file"
          fi
        done
        
        if [[ -n "$EXISTING_FILES" ]]; then
          echo "Creating module.zip with files: $EXISTING_FILES"
          zip -r module.zip $EXISTING_FILES
          echo "module.zip created successfully"
          ls -lh module.zip
        else
          echo "No files found to zip"
        fi

    - name: Analyze Bundle Size (Individual Files)
      uses: preactjs/compressed-size-action@v2
      with:
        repo-token: ${{ github.token }}
        pattern: ${{ inputs.pattern }}
        exclude: ${{ inputs.exclude }}
        strip-hash: ${{ inputs.strip-hash }}
        minimum-change-threshold: ${{ inputs.minimum-change-threshold }}
        
    - name: Analyze Bundle Size (Module Zip)
      if: inputs.analyze-zip == 'true'
      uses: preactjs/compressed-size-action@v2
      with:
        repo-token: ${{ github.token }}
        pattern: '${{ inputs.working-directory }}/module.zip'
        minimum-change-threshold: ${{ inputs.minimum-change-threshold }}