name: 'Foundry VTT Module Release'
description: 'Build and release Foundry VTT modules with automatic zip creation and artifact upload'
author: 'David Raynes'

inputs:
  tag:
    description: 'Tag name (optional - defaults to release event tag or latest git tag)'
    required: false

  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'

  github-packages:
    description: '(Deprecated) Previously toggled GitHub Packages authentication. No longer used.'
    required: false
    default: 'false'
  
  build-command:
    description: 'Build command to run'
    required: false
    default: 'npm run build'
  
  working-directory:
    description: 'Directory containing built files after build'
    required: false
    default: 'dist'
  
  module-files:
    description: 'Files and directories to include in module zip (space-separated, relative to working-directory)'
    required: true
    default: 'module.json styles/ templates/ languages/'
  
  zip-name:
    description: 'Name of the zip file to create'
    required: false
    default: 'module.zip'

outputs:
  version:
    description: 'The version number extracted from the git tag'
    value: ${{ steps.get_version.outputs.version-without-v }}
  
  zip-path:
    description: 'Path to the created module zip file'
    value: ${{ steps.create_zip.outputs.zip-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Determine tag
      id: get_tag
      shell: bash
      run: |
        # Use provided tag, fall back to release event, then git describe
        if [ -n "${{ inputs.tag }}" ]; then
          TAG="${{ inputs.tag }}"
          echo "📦 Using provided tag: $TAG"
        elif [ -n "${{ github.event.release.tag_name }}" ]; then
          TAG="${{ github.event.release.tag_name }}"
          echo "📦 Using release event tag: $TAG"
        else
          # Try to get the latest tag from git
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$TAG" ]; then
            echo "📦 Using git tag: $TAG"
          fi
        fi
        
        if [ -z "$TAG" ]; then
          echo "❌ Error: No tag found! Please provide tag input or run in release context"
          exit 1
        fi
        
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Extract version from tag
      id: get_version
      shell: bash
      run: |
        TAG="${{ steps.get_tag.outputs.tag }}"
        # Remove 'v' prefix if present
        VERSION="${TAG#v}"
        
        echo "version-without-v=$VERSION" >> $GITHUB_OUTPUT
        echo "version=v$VERSION" >> $GITHUB_OUTPUT
        echo "📦 Version extracted: $VERSION"

    - name: Build module
      shell: bash
      env:
        MODULE_VERSION: ${{ steps.get_version.outputs.version-without-v }}
        GH_PROJECT: ${{ github.repository }}
        GH_TAG: ${{ steps.get_tag.outputs.tag }}
        UPLOAD_SOURCE_MAPS: true
      run: ${{ inputs.build-command }}

    - name: Update module.json URLs for release
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        TAG="${{ steps.get_tag.outputs.tag }}"
        if [[ -f "module.json" ]]; then
          echo "📦 Updating module.json URLs for tag $TAG"
          
          # Replace latest URLs with tag-specific URLs
          sed -i.bak \
            -e "s|releases/latest/download/|releases/download/$TAG/|g" \
            module.json
          
          # Remove backup file
          rm -f module.json.bak
          
          echo "Updated module.json URLs:"
          grep -E "(manifest|download)" module.json || true
        else
          echo "⚠️ No module.json found in ${{ inputs.working-directory }}"
        fi

    - name: Create module zip
      id: create_zip
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Start with base module files
        FILES="${{ inputs.module-files }}"
        
        # Always add README.md and LICENSE if they exist
        if [[ -f "README.md" ]]; then
          FILES="$FILES README.md"
        fi
        
        if [[ -f "LICENSE" ]]; then
          FILES="$FILES LICENSE"
        fi
        
        echo "Creating zip with files: $FILES"
        zip -r "${{ inputs.zip-name }}" $FILES
        
        echo "zip-path=${{ inputs.working-directory }}/${{ inputs.zip-name }}" >> $GITHUB_OUTPUT

    - name: Upload Release Assets
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        TAG="${{ steps.get_tag.outputs.tag }}"
        
        # Check if this is a release event or if we need to upload manually
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "📦 Running in release event context - using ncipollo/release-action"
          # For backward compatibility, we'll create a separate step for this
        else
          echo "📦 Running in non-release context - checking if release exists"
          
          # Check if release exists
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "✅ Release $TAG found - uploading assets"
            
            # Upload the assets
            gh release upload "$TAG" \
              "${{ inputs.working-directory }}/module.json" \
              "${{ steps.create_zip.outputs.zip-path }}" \
              --clobber
              
            echo "✅ Assets uploaded successfully"
          else
            echo "⚠️ Release $TAG not found"
            echo "📁 Assets created at:"
            echo "   - ${{ inputs.working-directory }}/module.json"
            echo "   - ${{ steps.create_zip.outputs.zip-path }}"
            echo ""
            echo "ℹ️ To upload manually, create a release for tag $TAG"
          fi
        fi

    # For backward compatibility with release events
    - name: Update release with artifacts (release event)
      if: github.event_name == 'release'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ github.token }}
        artifacts: "${{ inputs.working-directory }}/module.json, ${{ steps.create_zip.outputs.zip-path }}"
        tag: ${{ steps.get_tag.outputs.tag }}
        body: ${{ github.event.release.body }}