name: 'Foundry VTT Module Release'
description: 'Build and release Foundry VTT modules with automatic zip creation and artifact upload'
author: 'David Raynes'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  
  build-command:
    description: 'Build command to run'
    required: false
    default: 'npm run build'
  
  working-directory:
    description: 'Directory containing built files after build'
    required: false
    default: 'dist'
  
  module-files:
    description: 'Files and directories to include in module zip (space-separated, relative to working-directory)'
    required: true
    default: 'module.json styles/ templates/ languages/'
  
  zip-name:
    description: 'Name of the zip file to create'
    required: false
    default: 'module.zip'

outputs:
  version:
    description: 'The version number extracted from the git tag'
    value: ${{ steps.get_version.outputs.version-without-v }}
  
  zip-path:
    description: 'Path to the created module zip file'
    value: ${{ steps.create_zip.outputs.zip-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: npm ci

    - name: Extract version from tag
      id: extract_version
      uses: damienaicheh/extract-version-from-tag-action@v1.3.0

    - name: Set version outputs
      id: get_version
      shell: bash
      run: |
        # Combine major.minor.patch to create full version
        FULL_VERSION="${{ steps.extract_version.outputs.major }}.${{ steps.extract_version.outputs.minor }}.${{ steps.extract_version.outputs.patch }}"
        
        # Add pre-release if it exists
        if [[ "${{ steps.extract_version.outputs.pre-release }}" != "" ]]; then
          FULL_VERSION="${FULL_VERSION}-${{ steps.extract_version.outputs.pre-release }}"
        fi
        
        echo "version-without-v=$FULL_VERSION" >> $GITHUB_OUTPUT
        echo "version=v$FULL_VERSION" >> $GITHUB_OUTPUT
        echo "Version extracted: $FULL_VERSION"

    - name: Build module
      shell: bash
      env:
        MODULE_VERSION: ${{ steps.get_version.outputs.version-without-v }}
        GH_PROJECT: ${{ github.repository }}
        GH_TAG: ${{ github.event.release.tag_name }}
        UPLOAD_SOURCE_MAPS: true
      run: ${{ inputs.build-command }}

    - name: Update module.json URLs for release
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ -f "module.json" ]]; then
          echo "Updating module.json URLs for tag ${{ github.event.release.tag_name }}"
          
          # Replace latest URLs with tag-specific URLs
          sed -i.bak \
            -e "s|releases/latest/download/|releases/download/${{ github.event.release.tag_name }}/|g" \
            module.json
          
          # Remove backup file
          rm -f module.json.bak
          
          echo "Updated module.json URLs:"
          grep -E "(manifest|download)" module.json || true
        else
          echo "No module.json found in ${{ inputs.working-directory }}"
        fi

    - name: Create module zip
      id: create_zip
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Start with base module files
        FILES="${{ inputs.module-files }}"
        
        # Always add README.md and LICENSE if they exist
        if [[ -f "README.md" ]]; then
          FILES="$FILES README.md"
        fi
        
        if [[ -f "LICENSE" ]]; then
          FILES="$FILES LICENSE"
        fi
        
        echo "Creating zip with files: $FILES"
        zip -r "${{ inputs.zip-name }}" $FILES
        
        echo "zip-path=${{ inputs.working-directory }}/${{ inputs.zip-name }}" >> $GITHUB_OUTPUT

    - name: Update release with artifacts
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ github.token }}
        artifacts: "${{ inputs.working-directory }}/module.json, ${{ steps.create_zip.outputs.zip-path }}"
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}